# Generated by Django 4.0.3 on 2022-04-20 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_module_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trash', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False)),
                ('sku', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product_price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('offer_price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('offer_start', models.DateTimeField(blank=True, null=True)),
                ('offer_end', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('next_stock_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_brand_products', to='basic_module_app.brand')),
                ('categories', models.ManyToManyField(related_name='get_category_products', to='basic_module_app.category')),
                ('collections', models.ManyToManyField(related_name='get_collection_products', to='basic_module_app.collection')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_type_products', to='basic_module_app.producttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trash', models.BooleanField(default=False)),
                ('sku', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product_price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_product_variations', to='product_app.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariationValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trash', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_product_variation_values', to='product_app.productvariation')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_variation_product_values', to='basic_module_app.variation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trash', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_product_requests', to='product_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_user_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trash', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='')),
                ('primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_product_images', to='product_app.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
