# Generated by Django 4.0.3 on 2022-06-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_productvariation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
