# Generated by Django 4.0.3 on 2022-07-02 20:35

from django.db import migrations, models
import product_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0010_alter_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=product_app.models.path_and_rename),
        ),
    ]
