# Generated by Django 4.0.3 on 2022-06-01 11:21

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_userotp_otp_alter_userotp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp',
            field=models.CharField(default=auth_app.models.key_generator, max_length=6),
        ),
    ]
