# Generated by Django 4.0.3 on 2022-06-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_userotp_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userotp',
            old_name='user',
            new_name='phone_number',
        ),
    ]
