# Generated by Django 4.0.5 on 2022-06-13 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Please provide a valid 11 digit phone number.', regex='(^(01)[3-9]\\d{8})$')]),
        ),
    ]
