# Generated by Django 4.0.3 on 2022-05-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
