# Generated by Django 4.0.3 on 2022-05-31 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_checkout_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutpayment',
            name='checkout',
        ),
        migrations.AlterField(
            model_name='checkoutpayment',
            name='tran_id',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_checkout_payment', to='user_app.checkout'),
        ),
    ]
