# Generated by Django 4.0.3 on 2022-05-31 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_remove_checkoutpayment_checkout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutpayment',
            name='id',
        ),
        migrations.AlterField(
            model_name='checkoutpayment',
            name='tran_id',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='get_checkout_payment', serialize=False, to='user_app.checkout'),
        ),
    ]
