# Generated by Django 4.0.5 on 2022-06-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_remove_checkoutpayment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='order_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Payment Process'), (1, 'Order placed'), (2, 'Processing'), (3, 'Packaging'), (4, 'On-way'), (5, 'Reached'), (6, 'Completed')], default=0),
        ),
    ]
