# Generated by Django 4.0.3 on 2022-05-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_module_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
