# Generated by Django 4.0.3 on 2022-06-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_module_app', '0002_coupon_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='asdf', upload_to='category'),
            preserve_default=False,
        ),
    ]
