# Generated by Django 4.0.5 on 2022-06-13 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_module_app', '0003_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trash', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='validate_date',
        ),
        migrations.CreateModel(
            name='CouponBank',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trash', models.BooleanField(default=False)),
                ('tran_id', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='get_user_coupon_payment', serialize=False, to='basic_module_app.usercoupon')),
                ('val_id', models.CharField(max_length=255)),
                ('card_no', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('card_issuer', models.CharField(blank=True, max_length=255, null=True)),
                ('card_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('card_sub_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('card_issuer_country', models.CharField(blank=True, max_length=255, null=True)),
                ('card_issuer_country_code', models.CharField(blank=True, max_length=255, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=255, null=True)),
                ('risk_title', models.CharField(blank=True, max_length=255, null=True)),
                ('store_id', models.CharField(max_length=255)),
                ('bank_tran_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('store_amount', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('card_type', models.CharField(max_length=255)),
                ('tran_date', models.DateTimeField()),
                ('currency', models.CharField(max_length=255)),
                ('currency_amount', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('currency_rate', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('base_fair', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_user_coupons', to='basic_module_app.coupon'),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_user_coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
