# Generated by Django 4.0.5 on 2022-06-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_module_app', '0004_usercoupon_remove_coupon_validate_date_couponbank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='free_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
