# Generated by Django 4.0.5 on 2022-06-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_module_app', '0006_usercoupon_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
