# Generated by Django 4.0.5 on 2022-06-13 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_module_app', '0007_coupon_price_usercoupon_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercoupon',
            old_name='completed',
            new_name='used',
        ),
    ]
