# Generated by Django 4.0.5 on 2022-06-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_module_app', '0008_rename_completed_usercoupon_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoupon',
            name='payment',
        ),
        migrations.DeleteModel(
            name='CouponBank',
        ),
    ]
