# Generated by Django 4.0.3 on 2022-06-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_module_app', '0011_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='name',
            new_name='text',
        ),
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
