# Generated by Django 4.0.3 on 2022-06-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_module_app', '0012_rename_name_banner_text_banner_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
