# Generated by Django 4.0.3 on 2022-07-02 19:40

import EcommerceClient.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_module_app', '0013_alter_banner_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(max_length=500, upload_to=EcommerceClient.mixins.get_file_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(max_length=500, upload_to=EcommerceClient.mixins.get_file_path),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=EcommerceClient.mixins.get_file_path),
        ),
    ]
