# Generated by Django 4.0.3 on 2022-07-05 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_module_app', '0014_alter_banner_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postoffice',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_district_post_offices', to='basic_module_app.district'),
        ),
        migrations.AlterField(
            model_name='postoffice',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_division_post_offices', to='basic_module_app.division'),
        ),
    ]
